apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: database-system
spec:
  clusterIP: None # Required for StatefulSets to maintain sticky DNS names
  selector:
    app: database
  ports:
    - port: 3306
      targetPort: 3306