apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: database-system
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: db-container
        image: 681504525746.dkr.ecr.us-east-2.amazonaws.com/database:4590c09d46416cb1829427f26bd6068685248a6c
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "supersecret"
        - name: MYSQL_DATABASE
          value: "ecommerceapp" # Tells MySQL to create this DB on startup
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi