apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-monolith
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-monolith
  template:
    metadata:
      labels:
        app: core-monolith
    spec:
      containers:
      - name: app-container
        image: 681504525746.dkr.ecr.us-east-2.amazonaws.com/core-monolith:58910e5c3c9be3c9ac187632c9f9e5402d46d0cb
        ports:
        - containerPort: 80