apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-monolith
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-monolith
  template:
    metadata:
      labels:
        app: core-monolith
    spec:
      containers:
      - name: app-container
        image: 681504525746.dkr.ecr.us-east-2.amazonaws.com/core-monolith:e7a11be7674c91a9a5349c9a33076bc940632965
        ports:
        - containerPort: 80