apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-monolith
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-monolith
  template:
    metadata:
      labels:
        app: core-monolith
    spec:
      containers:
      - name: app-container
        image: 681504525746.dkr.ecr.us-east-2.amazonaws.com/core-monolith:4590c09d46416cb1829427f26bd6068685248a6c
        ports:
        - containerPort: 80