# This is for local development only (for running Docker containers)
version: '3.8'

services:
  ecommercecache01:
    image: memcached:alpine
    restart: always

  ecommercemq01:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS:-guest}

  ecommerceapp:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/php-ecommerce-app:latest
    container_name: php-ecommerce-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - ecommercecache01
      - ecommercemq01